---
- name: Create directory to store keys
  file:
    name: /root/keys
    state: directory

- name: Download key for external package repository
  get_url:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    dest: /root/keys/google-chrome

- name: Install key for external package repository
  command: apt-key add /root/keys/google-chrome

- name: Add apt sources
  lineinfile:
    dest: '/etc/apt/sources.list.d/google-chrome.list'
    line: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    create: true

- name: update package repository
  command: apt-get update

- name: Infer current kernel Linux version
  command: uname -r
  register: kernel_version

- name: Install kernel Linux headers
  apt:
    name: linux-headers-{{kernel_version.stdout}}
    state: present
  notify: Restart system

- name: Install system packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - curl
    - dtrx
    - emacs-nox
    # In a future iteration of this project, the appropriate version of the
    # Mozilla Firefox browser will be installed as part of the testing
    # procedure.
    - firefox
    - git
    # In a future iteration of this project, the appropriate version of the
    # Google Chrome browser will be installed as part of the testing procedure.
    - google-chrome-stable
    - htop
    - libnss3-tools
    - nvidia-367
    - nvidia-375
    - nvidia-384
    - python-pip
    - python2.7
    - rsync
    - screen
    - unattended-upgrades
    - virtualenv
    - xauth
    - xvfb

- name: Create directory to store downloaded files
  file:
    name: ~/downloads
    state: directory

- name: Download Mozilla Geckodriver
  get_url:
    url: https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
    dest: ~/downloads/

- name: Extend hosts file with configuration to shunt Firefox requests
  lineinfile:
    dest: /etc/hosts
    line: '{{item}}'
  with_items:
    - 0.0.0.0 *.cdn.mozilla.net
    - 0.0.0.0 normandy.cdn.mozilla.net
    - 0.0.0.0 tiles.services.mozilla.com
    - 0.0.0.0 location.services.mozilla.com
    - 0.0.0.0 *.services.mozilla.com

- name: Install Mozilla Geckodriver
  unarchive:
    src: ~/downloads/geckodriver-v0.19.1-linux64.tar.gz
    dest: /usr/local/bin
    remote_src: true

- name: Download Google Chromedriver
  get_url:
    url: https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
    dest: ~/downloads/

- name: Install Google Chromedriver
  unarchive:
    src: ~/downloads/chromedriver_linux64.zip
    dest: /usr/local/bin
    remote_src: true
