---
- name: Unmount database partition
  command: umount {{db_device}}
  when: db_device_reformat
  ignore_errors: True

- name: Format database partition
  command: mkfs --type ext4 {{db_device}}
  when: db_device_reformat

- name: Enable database partition
  lineinfile:
    dest: /etc/fstab
    regexp: '^{{db_device}}\s'
    line: '{{db_device}} {{db_mount_point}} ext4 defaults 0 0'

- name: Determine if partition is mounted
  command: mountpoint {{db_mount_point}}
  ignore_errors: True
  register: check_partition

- name: Mount database partition
  command: mount {{db_device}}
  when: check_partition | failed

- name: Grant ownership of database mount point to application user
  command: chown -R {{application_user}} {{db_mount_point}}
