---
- name: Create a Buildbot worker
  command: |
    sudo --user {{application_user}}
        buildbot-worker create-worker {{home_dir}}/worker {{master_hostname}} {{application_user}} {{buildbot_worker_password}}
  args:
    chdir: '{{home_dir}}'
    creates: '{{home_dir}}/worker'

- name: Insert description of worker system
  template:
    src: host.j2
    owner: '{{application_user}}'
    group: '{{application_group}}'
    dest: '{{home_dir}}/worker/info/host'

- name: Define a system service
  template:
    src: buildbot-worker.service.j2
    dest: /etc/systemd/system/buildbot-worker.service
  notify:
    - Restart "build worker" service

- name: Enable system service
  systemd:
    name: buildbot-worker
    enabled: true
    state: started

- name: Install script for validating results
  copy:
    src: ../src/scripts/validate-wpt-results.py
    dest: /usr/local/bin/validate-wpt-results.py
    mode: 0755
